---
title: "Height_Profile"
author: "Flueckiger_Rubens"
date: "2025-04-01"
output: 
  html_document:
    toc: true
---

This file calculates the height profile along both the short and long route. Differences between the GPS device and the digital elevation model (DEM) are displayed.

# 1 Import packages and files

```{r, message=FALSE, warning=FALSE}
#Packages
library(ggplot2)

#Files
l_lap <- read.table("../data/Distanz_&_Hohe_GR.csv", sep = ";", header = T)
s_lap <- read.table("../data/Distanz_&_Hohe_KR.csv", sep = ";", header = T)
```

# 2 Plot

```{r, echo=FALSE}
#Color code
colors <- c("DEM_(Swisstopo)" = "black", "GPS_(Messwagen)" = "red")
```

Plot

```{r, echo=FALSE}
#Open jpeg
jpeg("../Images/Height_Profile/Height_Profiles.jpeg", height = 486, width = 1200, res = 108)

#Long Route
p1 <- ggplot(l_lap, aes(x = Distanz_Runsum)) + #x-Axis
  geom_line(aes(y = Height_GIS1, color = "DEM_(Swisstopo)")) + #DEM Line
  geom_line(aes(y = Height, color = "GPS_(Messwagen)")) + #GPS Line
  labs(y = "Höhe über Meer [m]", x = "Distanz [m]", color = " ") + #Axis Label & Legend
  ggtitle("Höhenprofil der langen Runde") + #Title
  scale_color_manual(values = colors) + #Color Legend
  theme_bw() + #Plot astetics
  theme(legend.position = "none") +
  annotate(geom = "label", x = 0, y = 598, label = "a", family = "serif", size = 6) + #Plot number
  theme(plot.margin = margin(0.2, 2.2, 0.2, 0.2, "cm")) + #Set Plot margins
  theme(plot.title = element_text(hjust = 0.5)) #Center title

#Short Route
p2 <- ggplot(s_lap, aes(x = Distanz_Runsum)) + #x-Axis
  geom_line(aes(y = Height_GIS1, color = "DEM_(Swisstopo)")) + #DEM Line
  geom_line(aes(y = Height, color = "GPS_(Messwagen)")) + #GPS Line
  labs(y = "Höhe über Meer [m]", x = "Distanz [m]", color = " ") + #Axis Label & Legend
  ggtitle("Höhenprofil der kurzen Runde") + #Title
  scale_color_manual(values = colors) + #Color Legend
  theme_bw() + #Plot astetics
  annotate(geom = "label", x = 500, y = 575.5, label = "b", family = "serif", size = 6) + #Plot number
  theme(plot.margin = margin(0.2, 0.1, 0.2, -1.3, "cm")) + #Set Plot margins
  theme(plot.title = element_text(hjust = 0.5)) #Center title

#Combine both plots
cowplot::plot_grid(p1, p2)

#Close and save jpeg
dev.off()
```
```{r, echo=FALSE, fig.align='center', fig.cap="Fig. 1: Height profile along the long route (left) and the short route (right)", fig.width=10, fig.height=4}
cowplot::plot_grid(p1, p2)
```

